In [297]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import copy

In [298]:
df = pd.read_csv("Housing.csv")[["price","area","bathrooms","bedrooms"]]

In [299]:
df.head()

price  area  bathrooms  bedrooms
0  13300000  7420          2         4
1  12250000  8960          4         4
2  12250000  9960          2         3
3  12215000  7500          2         4
4  11410000  7420          1         4

In [300]:
y_train = np.array(df["price"])
x_train = np.array(df.drop("price", axis = 1))

In [301]:
#x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
#y_train = np.array([460, 232, 178])

In [302]:
w_actual = np.array([4,5,2])
b_actual = 30

In [303]:
w_init = np.zeros((x_train.shape[1],))
b_init = 0.0

In [304]:
w_init

array([0., 0., 0.])

In [305]:
x_train.shape

(545, 3)

In [306]:
def calc_cost(x,y, w, b):


    m = x_train.shape[0]
    cost = 0.0
    for i in range(m):
        f_w_b = np.dot(w,x[i]) + b
        cost += (f_w_b - y[i])**2
    return (1/(2*m))*cost


In [307]:
cost = calc_cost(x_train, y_train, w_init, b_init)

In [308]:
cost

np.float64(13106916364659.268)

In [309]:
def calc_grad(x,y,w,b):
    m = x_train.shape[0]
    n = x_train.shape[1]
    grad_w = np.zeros((x.shape[1],))
    grad_b = 0.0
    for i in range(m):
        cost = (np.dot(w,x_train[i]) + b) - y[i]
        grad_b += cost
        for j in range(n):
            grad_w[j] = grad_w[j] + (cost*x[i,j] )

    return (grad_w/m), (grad_b/m)


In [310]:
w_init, b_init = calc_grad(x_train, y_train, w_init, b_init)
w_init

array([-2.67229201e+10, -6.61666767e+06, -1.46390263e+07])

In [311]:
def Gradient_Descent(x,y,w_init,b_init,lr, steps):

    cost_hist = []

    w = copy.deepcopy(w_init)
    b = b_init

    for i in range(steps):
        err = calc_cost(x,y,w, b)
        cost_hist.append(err)
        grad_w, grad_b = calc_grad(x,y,w,b)
        w = w - (lr*grad_w)
        b = b - (lr*grad_b)

        if i%1000 ==0:
            print(f"Cost: {err}")

    return w, b, cost_hist



In [315]:
#weight, bias, costs = Gradient_Descent(x_train, y_train, w_init, b_init, calc_cost, calc_grad, 5.0e-7, 200000)
weight, bias, costs = Gradient_Descent(x_train, y_train, w_init, b_init, 5.0e-10, 10000)

Cost: 1.1150529638043803e+28
Cost: 245347875164369.75
Cost: 6714808090635.276
Cost: 6714797070590.859
Cost: 6714786050572.98
Cost: 6714775030576.511
Cost: 6714764010601.468
Cost: 6714752990647.847
Cost: 6714741970715.65
Cost: 6714730950804.864


In [ ]:
weight

array([  0.22657412,   4.52855109, -12.71471414,  -0.96942035])